# Generated by Django 5.0.7 on 2024-09-17 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryname', models.CharField(max_length=100, null=True)),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('emailid', models.CharField(max_length=100, null=True)),
                ('contact', models.CharField(max_length=15, null=True)),
                ('message', models.CharField(max_length=300, null=True)),
                ('msgdate', models.DateField(null=True)),
                ('isread', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PassNumber', models.CharField(max_length=200)),
                ('FullName', models.CharField(max_length=200, null=True)),
                ('ContactNumber', models.CharField(max_length=15, null=True)),
                ('Email', models.CharField(max_length=100, null=True)),
                ('IdentityType', models.CharField(max_length=200, null=True)),
                ('IdentityCardno', models.CharField(max_length=200, null=True)),
                ('Source', models.CharField(max_length=300, null=True)),
                ('Destination', models.CharField(max_length=300, null=True)),
                ('FromDate', models.DateField(null=True)),
                ('ToDate', models.DateField(null=True)),
                ('Cost', models.CharField(max_length=300, null=True)),
                ('PasscreationDate', models.DateTimeField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pass_management.category')),
            ],
        ),
    ]
